export const ERROR_CODES = {
  INVALID_URL: 'INVALID_URL',
  INVALID_REACTION: 'INVALID_REACTION',
  NO_COIN: 'NO_COIN',
  MAINTENANCE: 'MAINTENANCE',
  QUEUE_FULL: 'QUEUE_FULL',
  QUEUE_TIMEOUT: 'QUEUE_TIMEOUT',
  SERVICE_BUSY: 'SERVICE_BUSY',
  UPSTREAM_ERROR: 'UPSTREAM_ERROR',
  RATE_LIMIT: 'RATE_LIMIT',
  INVALID_KEY: 'INVALID_KEY',
  EXPIRED_KEY: 'EXPIRED_KEY',
  HOST_NOT_ALLOWED: 'HOST_NOT_ALLOWED',
  TERMS_REQUIRED: 'TERMS_REQUIRED',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
};

const STATUS_MAP = {
  INVALID_URL: 400, INVALID_REACTION: 400, NO_COIN: 402, MAINTENANCE: 503,
  QUEUE_FULL: 429, QUEUE_TIMEOUT: 504, SERVICE_BUSY: 503, UPSTREAM_ERROR: 502,
  RATE_LIMIT: 429, INVALID_KEY: 401, EXPIRED_KEY: 401, HOST_NOT_ALLOWED: 403,
  TERMS_REQUIRED: 400, DUPLICATE_REQUEST: 409, UNAUTHORIZED: 401, FORBIDDEN: 403,
  VALIDATION_ERROR: 400, METHOD_NOT_ALLOWED: 405, INTERNAL_ERROR: 500, NOT_FOUND: 404,
};

export function sendError(res, code, message, extra) {
  const status = STATUS_MAP[code] || 400;
  res.status(status).json({ success: false, code, message, ...(extra || {}) });
}

export function sendSuccess(res, data, status = 200) {
  res.status(status).json({ success: true, ...data });
}
